on: 
  push:
    branches:
      - 'master'
name: Build and deploy to Azure Web App

jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master            
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            ls
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/wrongmove:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/wrongmove:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/wrongmove:${{ github.sha }}      
            
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'wrongmove'
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/wrongmove:${{ github.sha }}'
